---
apiVersion: v1
kind: Namespace
metadata:
  name: pso-analytics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pso-collect
  namespace: pso-analytics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pso-collect
rules:
- apiGroups: ["", "apps"]
  resources: ["persistentvolumeclaims", "statefulsets", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pso-collect
  namespace: pso-analytics
subjects:
- kind: ServiceAccount
  name: pso-collect
  namespace: pso-analytics
roleRef:
  kind: ClusterRole
  name: pso-collect
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pso-collect-secret
  namespace: pso-analytics
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pso-collect-secret
  namespace: pso-analytics
subjects:
- kind: ServiceAccount
  name: pso-collect
  namespace: pso-analytics
roleRef:
  kind: ClusterRole
  name: pso-collect-secret
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pso-analytics
  namespace: pso-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pso-collect
  template:
    metadata:
      labels:
        app: pso-collect
    spec:
      serviceAccountName: pso-collect
      containers:
      - name: collect
        image: joshuarobinson/pso-analytics:0.2
        command: ["python"]
        args: ["collect_storage_info.py", "--poll-seconds", "3600"]
        imagePullPolicy: Always
      restartPolicy: Always
